import Head from 'next/head'
import { useRouter } from 'next/router'
import SideBar from '@/components/SideBar'
import VideoRec from '@/components/VideoRec'
import { useState, useEffect } from 'react'
import axios from 'axios'
import { Skeleton } from '@mantine/core'

export default function Home() {
  const router = useRouter();
  // if (typeof window !== 'undefined') {
  //   if(localStorage.getItem('token') === null) {
  //     router.push('/login');
  //   }
  // }
  const [calls, setCalls] = useState([
    
  ]);
  useEffect(() => {
    const populateCalls = () => {
      const data = axios.get('api/meetings')
        .then((response) => {
          setCalls(response.data.meetings)
          console.log(calls)
        })
        .catch((err) => {
          console.log(err);
        })
      }
    populateCalls();
  }, [])
  
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{display: 'flex'}}>
        <SideBar calls={calls.length > 0 ? calls : []} act="All Calls"/>
        <div style={{marginLeft: '250px', height: '100%', width: '50%'}}>
          <h1 >
            All Calls
          </h1>
        
          { 
            calls.length > 0 ?
             calls.map((item) =>  {
              return (
                <>
                    <VideoRec item={item} key={item.id}/>
                    <br/>
                </>
              )
            })  : <>
            <Skeleton height={50} circle mb="xl" />
            <Skeleton height={8} radius="xl" />
            <Skeleton height={8} mt={6} radius="xl" />
            <Skeleton height={8} mt={6} width="70%" radius="xl" />
            <br/>
            <Skeleton height={50} circle mb="xl" />
            <Skeleton height={8} radius="xl" />
            <Skeleton height={8} mt={6} radius="xl" />
            <Skeleton height={8} mt={6} width="70%" radius="xl" />
            <br/>
            <Skeleton height={50} circle mb="xl" />
            <Skeleton height={8} radius="xl" />
            <Skeleton height={8} mt={6} radius="xl" />
            <Skeleton height={8} mt={6} width="70%" radius="xl" />
            <br/>
            <Skeleton height={50} circle mb="xl" />
            <Skeleton height={8} radius="xl" />
            <Skeleton height={8} mt={6} radius="xl" />
            <Skeleton height={8} mt={6} width="70%" radius="xl" />
            <br/>
          
          </>
           
          }
         
        </div>
      </div>
    </>
  )
}
